---
# we use docker as plateform
driver:
  name: vagrant

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

platforms:
  # Provisioning of Ansible server where ansible playbook will be launched
  - name: ubuntu-18.04
    driver:
      network:
        - [ 'private_network', { ip: '172.28.128.10' } ]
    provisioner:
      name: ansible_playbook
      ansible_connection: winrm
      ansible_inventory: tests/inventory
      requirements_path: requirements.yml
      require_windows_support: true
      require_chef_for_busser: false
      ansible_host_key_checking: false
      idempotency_test: true
      playbook: tests/test.yml
    verifier:
      name: shell
      command: echo 'Skipping Verify'

  # Target Windows 2016 to test
  - name: windows-2k16
    driver:
      box: diodonfrost/windows-2k16
      provision: true
      communicator: winrm
      network:
        - [ 'private_network', { ip: '172.28.128.11' } ]
      customize:
        memory: 2048
      vagrantfiles:
        - tests/vagrant/vagrant_windows_target.rb
    transport:
      name: winrm
    provisioner:
      name: shell

suites:
  - name: default
