source "https://rubygems.org"

gem "test-kitchen"
gem "kitchen-ansible"
gem "kitchen-docker"
gem "kitchen-inspec"
gem "kitchen-vagrant"
gem "kitchen-sync"
gem "inspec", "3.9"
gem "net-scp", "1.2.0"
gem "train"
