---
# Install selected packages

- name: Install chocolatey
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ default_packages }}"

- name: Install audio packages
  import_tasks: audio-packages.yml
  when: audio_install
  tags: audio

- name: Install cloud packages
  import_tasks: cloud-packages.yml
  when: cloud_install
  tags: cloud

- name: Install development packages
  import_tasks: development-packages.yml
  when: development_install
  tags: development

- name: Install network packages
  import_tasks: network-packages.yml
  when: network_install
  tags: network
