---
# Install selected packages

- name: Install chocolatey
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ default_packages }}"

- name: Install development packages
  import_tasks: development-packages.yml
  when: development_install
  tags: development

- name: Install audio packages
  import_tasks: audio-packages.yml
  when: audio_install
  tags: audio
