---
# Install text editor atom

- name: Install text editor Atom
  win_chocolatey:
    name: atom
    state: present

- name: Install Atom module with Atom Package Manager
  win_shell: "apm install {{ item }}"
  args:
    creates: '%HOMEPATH%\.atom\packages\{{ item }}'
  with_items: "{{ atom_packages }}"
